SUD-144 Add route /get_task
balex89/sudoku-solver-frontend pull request #12
Opened 2021-12-03 08:04 UTC by KalinovSergey

2021-12-04 18:14 UTC, balex89 requested changes

2021-12-04 18:14 UTC, balex89 commented on app/routes.py
> +        url=SOLVER_API_URL + "/v1/get_task",
проверить `SOLVER_API_URL` на предмет наличия там суффикса `/v1`

2021-12-05 13:29 UTC, KalinovSergey commented on app/routes.py
> +        url=SOLVER_API_URL + "/v1/get_task",
если я правильно понял, то задается это в sudokuFrontend.ini и суффикс /v1 там есть:
[solverService]
host = localhost
port = 5000
**api_version = v1**
api_url = http://%(host)s:%(port)s/%**(api_version)**s

В коде поправил, новый коммит запушил

2021-12-06 07:14 UTC, balex89 approved these changes

2021-12-06 07:18 UTC, merged