SUD-120 Add /validate route
balex89/sudoku-solver-frontend pull request #4
Opened 2021-10-04 08:42 UTC by KalinovSergey

2021-10-04 08:47 UTC, balex89 commented
Добавить автотест по аналогии с https://github.com/balex89/sudoku-solver/tree/master/tests
Потребуется conftest.py и test_app.py.

2021-10-05 19:57 UTC, KalinovSergey commented
Нужна помощь:
автотест написал, но все данные записал в path=.... Автотест работает, но некрасиво. Не нашел, как правильно передать в запрос отдельно значение параметра. Пробовал response = client.get(path="/validate", params = {"numbers" : 111}) и 
response = client.get(path="/validate", params = json.dumps({"numbers" : 111})) . Не принимает такой запрос. Пишет unexpected keyword params

2021-10-07 19:35 UTC, balex89 requested changes

2021-10-07 19:35 UTC, balex89 commented on app/routes.py
> +        return jsonify(is_valid=False)
пока убрать

2021-10-07 19:35 UTC, balex89 commented on tests/test_app.py
> +                          query_string={"numbers": "10000000"
```suggestion
                          query_string={"numbers": "100000000"
```

2021-10-07 19:35 UTC, balex89 commented on tests/test_app.py
> +        "Content-Type": mimetype,
удалить

2021-10-07 19:35 UTC, balex89 commented on tests/test_app.py
> +    assert response.mimetype == mimetype
поменять порядок проверок

2021-10-11 09:20 UTC, merged